In [1]:
import pandas as pd
df1=pd.read_csv("C:\\Users\\Ankit Rai\\Downloads\\stock\\stock_data6.csv")
df2=pd.read_csv("C:\\Users\\Ankit Rai\\Downloads\\stock\\hourly_market_trends_with_directions.csv")

In [2]:
df1

,date,message,Sentiment
0,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,Positive
1,2021-08-17 03:47:09+00:00,meghmani organic meghmani organic limited megh...,Negative
2,2021-08-17 03:47:09+00:00,sporting annual report china yarn ban lower in...,Negative
3,2021-08-17 03:47:09+00:00,railed gets worth orders,Positive
4,2021-08-17 03:47:09+00:00,barque nations sources says valuation process ...,Positive
...,...,...,...
30961,2024-11-26 05:49:18+00:00,crystal integrated services bags order bc,Neutral
30962,2024-12-02 03:58:51+00:00,cochon shipyards shares gain signing contract ...,Positive
30963,2024-12-02 03:59:18+00:00,rajasthan gases cells stake gujarat natural re...,Positive
30964,2024-12-04 04:00:00+00:00,revolt motor nov sales jump revolt motor repor...,Positive
30965,2024-12-04 04:00:07+00:00,china cabin november services mi vs mon,Neutral

In [3]:
df2

                 Timestamp  Hourly_Market_Index  Direction
0      2021-01-01 00:00:00           689.482551  No Change
1      2021-01-01 01:00:00           689.482551  Decreased
2      2021-01-01 02:00:00           689.482551  Decreased
3      2021-01-01 03:00:00           689.482551  Decreased
4      2021-01-01 04:00:00           689.482551  Decreased
...                    ...                  ...        ...
20779  2024-07-05 19:00:00          1412.416915  Increased
20780  2024-07-05 20:00:00          1412.626295  Increased
20781  2024-07-05 21:00:00          1412.835675  Increased
20782  2024-07-05 22:00:00          1413.045055  Increased
20783  2024-07-05 23:00:00          1413.254435  Increased

[20784 rows x 3 columns]

In [4]:
df1['Datetime'] = pd.to_datetime(df1['date']).dt.date

# Convert 'Date' in df2 to datetime object and extract date (just in case, though it may already be in the correct format)
df2['Datetime'] = pd.to_datetime(df2['Timestamp']).dt.date

In [5]:
df1

,date,message,Sentiment,Datetime
0,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,Positive,2021-08-17
1,2021-08-17 03:47:09+00:00,meghmani organic meghmani organic limited megh...,Negative,2021-08-17
2,2021-08-17 03:47:09+00:00,sporting annual report china yarn ban lower in...,Negative,2021-08-17
3,2021-08-17 03:47:09+00:00,railed gets worth orders,Positive,2021-08-17
4,2021-08-17 03:47:09+00:00,barque nations sources says valuation process ...,Positive,2021-08-17
...,...,...,...,...
30961,2024-11-26 05:49:18+00:00,crystal integrated services bags order bc,Neutral,2024-11-26
30962,2024-12-02 03:58:51+00:00,cochon shipyards shares gain signing contract ...,Positive,2024-12-02
30963,2024-12-02 03:59:18+00:00,rajasthan gases cells stake gujarat natural re...,Positive,2024-12-02
30964,2024-12-04 04:00:00+00:00,revolt motor nov sales jump revolt motor repor...,Positive,2024-12-04
30965,2024-12-04 04:00:07+00:00,china cabin november services mi vs mon,Neutral,2024-12-04

In [6]:
df2

                 Timestamp  Hourly_Market_Index  Direction    Datetime
0      2021-01-01 00:00:00           689.482551  No Change  2021-01-01
1      2021-01-01 01:00:00           689.482551  Decreased  2021-01-01
2      2021-01-01 02:00:00           689.482551  Decreased  2021-01-01
3      2021-01-01 03:00:00           689.482551  Decreased  2021-01-01
4      2021-01-01 04:00:00           689.482551  Decreased  2021-01-01
...                    ...                  ...        ...         ...
20779  2024-07-05 19:00:00          1412.416915  Increased  2024-07-05
20780  2024-07-05 20:00:00          1412.626295  Increased  2024-07-05
20781  2024-07-05 21:00:00          1412.835675  Increased  2024-07-05
20782  2024-07-05 22:00:00          1413.045055  Increased  2024-07-05
20783  2024-07-05 23:00:00          1413.254435  Increased  2024-07-05

[20784 rows x 4 columns]

In [7]:
merged_df = pd.merge(df1, df2, on='Datetime', how='inner')

In [8]:
merged_df

,date,message,Sentiment,Datetime,Timestamp,Hourly_Market_Index,Direction
0,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,Positive,2021-08-17,2021-08-17 00:00:00,869.374402,Decreased
1,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,Positive,2021-08-17,2021-08-17 01:00:00,869.403596,Increased
2,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,Positive,2021-08-17,2021-08-17 02:00:00,869.432790,Increased
3,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,Positive,2021-08-17,2021-08-17 03:00:00,869.461984,Increased
4,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,Positive,2021-08-17,2021-08-17 04:00:00,869.491177,Increased
...,...,...,...,...,...,...,...
646267,2024-07-05 04:13:38+00:00,poonawalla fincorp q disbursements grow core a...,Positive,2024-07-05,2024-07-05 19:00:00,1412.416915,Increased
646268,2024-07-05 04:13:38+00:00,poonawalla fincorp q disbursements grow core a...,Positive,2024-07-05,2024-07-05 20:00:00,1412.626295,Increased
646269,2024-07-05 04:13:38+00:00,poonawalla fincorp q disbursements grow core a...,Positive,2024-07-05,2024-07-05 21:00:00,1412.835675,Increased
646270,2024-07-05 04:13:38+00:00,poonawalla fincorp q disbursements grow core a...,Positive,2024-07-05,2024-07-05 22:00:00,1413.045055,Increased
646271,2024-07-05 04:13:38+00:00,poonawalla fincorp q disbursements grow core a...,Positive,2024-07-05,2024-07-05 23:00:00,1413.254435,Increased

In [9]:
merged_df.dropna()

,date,message,Sentiment,Datetime,Timestamp,Hourly_Market_Index,Direction
0,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,Positive,2021-08-17,2021-08-17 00:00:00,869.374402,Decreased
1,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,Positive,2021-08-17,2021-08-17 01:00:00,869.403596,Increased
2,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,Positive,2021-08-17,2021-08-17 02:00:00,869.432790,Increased
3,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,Positive,2021-08-17,2021-08-17 03:00:00,869.461984,Increased
4,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,Positive,2021-08-17,2021-08-17 04:00:00,869.491177,Increased
...,...,...,...,...,...,...,...
646267,2024-07-05 04:13:38+00:00,poonawalla fincorp q disbursements grow core a...,Positive,2024-07-05,2024-07-05 19:00:00,1412.416915,Increased
646268,2024-07-05 04:13:38+00:00,poonawalla fincorp q disbursements grow core a...,Positive,2024-07-05,2024-07-05 20:00:00,1412.626295,Increased
646269,2024-07-05 04:13:38+00:00,poonawalla fincorp q disbursements grow core a...,Positive,2024-07-05,2024-07-05 21:00:00,1412.835675,Increased
646270,2024-07-05 04:13:38+00:00,poonawalla fincorp q disbursements grow core a...,Positive,2024-07-05,2024-07-05 22:00:00,1413.045055,Increased
646271,2024-07-05 04:13:38+00:00,poonawalla fincorp q disbursements grow core a...,Positive,2024-07-05,2024-07-05 23:00:00,1413.254435,Increased

In [10]:
merged_df['Sentiment'] = merged_df['Sentiment'].map({'Positive': 1, 'Negative': -1, 'Neutral': 0})
merged_df['Direction'] = merged_df['Direction'].map({'Increased': 1, 'Decreased': -1, 'No Change': 0})

In [11]:
merged_df

,date,message,Sentiment,Datetime,Timestamp,Hourly_Market_Index,Direction
0,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,1,2021-08-17,2021-08-17 00:00:00,869.374402,-1
1,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,1,2021-08-17,2021-08-17 01:00:00,869.403596,1
2,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,1,2021-08-17,2021-08-17 02:00:00,869.432790,1
3,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,1,2021-08-17,2021-08-17 03:00:00,869.461984,1
4,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,1,2021-08-17,2021-08-17 04:00:00,869.491177,1
...,...,...,...,...,...,...,...
646267,2024-07-05 04:13:38+00:00,poonawalla fincorp q disbursements grow core a...,1,2024-07-05,2024-07-05 19:00:00,1412.416915,1
646268,2024-07-05 04:13:38+00:00,poonawalla fincorp q disbursements grow core a...,1,2024-07-05,2024-07-05 20:00:00,1412.626295,1
646269,2024-07-05 04:13:38+00:00,poonawalla fincorp q disbursements grow core a...,1,2024-07-05,2024-07-05 21:00:00,1412.835675,1
646270,2024-07-05 04:13:38+00:00,poonawalla fincorp q disbursements grow core a...,1,2024-07-05,2024-07-05 22:00:00,1413.045055,1
646271,2024-07-05 04:13:38+00:00,poonawalla fincorp q disbursements grow core a...,1,2024-07-05,2024-07-05 23:00:00,1413.254435,1

In [12]:
negative_count = merged_df[merged_df["Sentiment"] == -1].shape[0]
negative_count

125832

In [13]:
merged_df = merged_df.dropna()

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score

# Load your dataset
# For this example, I assume you already have a `merged_df` DataFrame with the 'message' and 'Sentiment' columns.
# Replace this with the code to load your actual data
# merged_df = pd.read_csv('your_dataset.csv')

# Ensure 'date' column is properly formatted
merged_df.loc[:, 'date'] = pd.to_datetime(merged_df['date'])

# Drop any rows with missing values in 'message' or 'Sentiment'
merged_df.dropna(subset=['message', 'Sentiment'], inplace=True)

# Split the data into features (X) and target (y)
X = merged_df['message']  # The text data
y = merged_df['Sentiment']  # The sentiment labels

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
vectorizer = CountVectorizer(stop_words='english') 
X_train_vect = vectorizer.fit_transform(X_train)
X_test_vect = vectorizer.transform(X_test)

# Initialize the Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model using the training data
rf_classifier.fit(X_train_vect, y_train)

# Predict on the test set
y_pred = rf_classifier.predict(X_test_vect)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')


cv_scores = cross_val_score(rf_classifier, X_train_vect, y_train, cv=5)
print(f'Cross-Validation Scores: {cv_scores}')
print(f'Mean Cross-Validation Score: {cv_scores.mean():.2f}')

C:\Users\Ankit Rai\AppData\Local\Temp\ipykernel_12932\1552880857.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df.loc[:, 'date'] = pd.to_datetime(merged_df['date'])
C:\Users\Ankit Rai\AppData\Local\Temp\ipykernel_12932\1552880857.py:14: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  merged_df.loc[:, 'date'] = pd.to_datetime(merged_df['date'])
C:\Users\Ankit Rai\AppData\Local\Temp\ipykernel_12932\1552880857.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df.dropna(subset=['message', 'Sentiment'], inplace=True)

Accuracy: 99.97%
Cross-Validation Scores: [0.99978723 0.9998646  0.99984526 0.99980657 0.99985493]
Mean Cross-Validation Score: 1.00

In [15]:
print(X_train_vect.shape)
print(y_train.shape)

(516979, 20717)
(516979,)

In [16]:
import joblib

# Save the trained RandomForest model
joblib.dump(rf_classifier, 'sentiment_model.joblib')

# Save the vectorizer as well, so that you can use it to transform new messages later
joblib.dump(vectorizer, 'count_vectorizer.joblib')

['count_vectorizer.joblib']

In [21]:
# Example text to check sentiment
custom_text = """Shares drop following regulatory concerns"""

# Preprocess and vectorize the custom text
custom_text_vect = vectorizer.transform([custom_text])  # Use the trained vectorizer
custom_pred = rf_classifier.predict(custom_text_vect)  # Predict sentiment

# Output the sentiment
print(f"Sentiment of the custom text: {custom_pred[0]}")

Sentiment of the custom text: -1

In [22]:
# Example text to check sentiment
custom_text = """Rupee strengthens against the US dollar"""

# Preprocess and vectorize the custom text
custom_text_vect = vectorizer.transform([custom_text])  # Use the trained vectorizer
custom_pred = rf_classifier.predict(custom_text_vect)  # Predict sentiment

# Output the sentiment
print(f"Sentiment of the custom text: {custom_pred[0]}")

Sentiment of the custom text: 1

In [25]:
results_df = pd.DataFrame({
    'Message': X_test,  # The message text from the test set
    'Actual Sentiment': y_test,  # The actual sentiment from the test set
    'Predicted Sentiment': y_pred,  # The predicted sentiment from the model
    'Direction': merged_df.loc[X_test.index, 'Direction']  # Match the 'Direction' for the test data
})
results_df

,Message,Actual Sentiment,Predicted Sentiment,Direction
608180,delivery co joins hands pe firm nexus ventures...,1,1,1
159603,motile usual real estate commit core motile us...,1,1,1
524113,asia markets asiapacific markets lower wednesd...,-1,-1,-1
633029,hart electronics q net profit rose core versus...,1,1,1
479574,human ind board meet dec consider approve prop...,0,0,1
...,...,...,...,...
45749,buy britannica industries target sharekhan sto...,1,1,1
254372,pvrcinepolis india talks merger says sources u...,-1,-1,-1
552179,sonya roshni q sons net profit rubles b vs big...,1,1,1
291065,tomato co says cooperating ici investigation n...,0,0,1
422121,si raises b rubles cross bonds,0,0,1