In [1]:
import pandas as pd
df1=pd.read_csv("C:\\Users\\Ankit Rai\\Downloads\\stock\\data2_cleaned.csv")

In [2]:
df1

,date,message
0,2024-12-04 04:00:07+00:00,china cabin november services mi vs mon
1,2024-12-04 04:00:00+00:00,revolt motor nov sales jump revolt motor repor...
2,2024-12-02 03:59:18+00:00,rajasthan gases cells stake gujarat natural re...
3,2024-12-02 03:58:51+00:00,cochon shipyards shares gain signing contract ...
4,2024-11-26 05:49:18+00:00,crystal integrated services bags order bc
...,...,...
9991,2022-10-03 03:09:36+00:00,shabby company whollyowned subsidiary mars med...
9992,2022-10-03 03:09:35+00:00,palmar sonya face stocks concessions custom du...
9993,2022-10-03 03:09:35+00:00,concord indian railways records best ever sept...
9994,2022-10-03 03:09:35+00:00,sterile teach st unveils g common help indian ...
9995,2022-10-03 03:09:35+00:00,sterile teach st launched multiverse indians f...

In [4]:
df2=pd.read_csv("C:\\Users\\Ankit Rai\\Downloads\\stock\\data2_cleaned2.csv")
df2

,date,message
0,2022-10-03 03:09:35+00:00,add foods add foods acquired stake telluric fo...
1,2022-10-03 03:09:35+00:00,hart hittel network ii limited whollyowned sub...
2,2022-10-03 03:08:29+00:00,india trillion onestop solution plan snatch fa...
3,2022-10-02 12:01:20+00:00,bazaar teach board directors subsidiary halapl...
4,2022-10-02 12:01:20+00:00,macrotech de real estate stocks lumbar sept mo...
...,...,...
14981,2021-11-18 03:25:42+00:00,india ms economist outlook growth recover gain...
14982,2021-11-18 03:25:42+00:00,also iii pre life perform target price remains...
14983,2021-11-18 03:25:42+00:00,institutions net sold fig bought k calls calls...
14984,2021-11-18 03:25:42+00:00,stocks news part operator one communications c...
14985,2021-11-18 02:21:47+00:00,important board meet tomorrow easy trip plante...

In [5]:
df3=pd.read_csv("C:\\Users\\Ankit Rai\\Downloads\\stock\\data2_cleaned3.csv")
df3

,date,message
0,2021-11-18 02:21:46+00:00,manufacturing front page industries coats incl...
1,2021-11-18 02:21:46+00:00,indigo airline effective nov passengers able b...
2,2021-11-17 09:56:18+00:00,see privatisation year back investment due dil...
3,2021-11-17 09:56:18+00:00,real estate stocks anus pure chairman anarock ...
4,2021-11-17 09:56:18+00:00,finance ministry close stake sale bell si year...
...,...,...
5979,2021-08-17 03:47:09+00:00,sporting annual report china yarn ban lower in...
5980,2021-08-17 03:47:09+00:00,sugar stocks sugar prices india rises various ...
5981,2021-08-17 03:47:09+00:00,barque nations sources says valuation process ...
5982,2021-08-17 03:47:09+00:00,railed gets worth orders
5983,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...

In [6]:
import pandas as pd

# Assuming df1, df2, and df3 are already defined and loaded

# Concatenate the dataframes
merged_df = pd.concat([df1, df2, df3], ignore_index=True)

# Optionally, sort by the 'date' column if you want them ordered chronologically
merged_df['date'] = pd.to_datetime(merged_df['date'])
merged_df = merged_df.sort_values(by='date', ascending=True).reset_index(drop=True)

# Display the merged dataframe
print(merged_df)

                           date  \
0     2021-08-17 03:39:23+00:00
1     2021-08-17 03:47:09+00:00
2     2021-08-17 03:47:09+00:00
3     2021-08-17 03:47:09+00:00
4     2021-08-17 03:47:09+00:00
...                         ...
30961 2024-11-26 05:49:18+00:00
30962 2024-12-02 03:58:51+00:00
30963 2024-12-02 03:59:18+00:00
30964 2024-12-04 04:00:00+00:00
30965 2024-12-04 04:00:07+00:00

                                                 message
0      pledge share details aurobindo parma promoter ...
1      meghmani organic meghmani organic limited megh...
2      sporting annual report china yarn ban lower in...
3                               railed gets worth orders
4      barque nations sources says valuation process ...
...                                                  ...
30961          crystal integrated services bags order bc
30962  cochon shipyards shares gain signing contract ...
30963  rajasthan gases cells stake gujarat natural re...
30964  revolt motor nov sales jump revolt motor repor...
30965            china cabin november services mi vs mon

[30966 rows x 2 columns]

In [7]:
merged_df

,date,message
0,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...
1,2021-08-17 03:47:09+00:00,meghmani organic meghmani organic limited megh...
2,2021-08-17 03:47:09+00:00,sporting annual report china yarn ban lower in...
3,2021-08-17 03:47:09+00:00,railed gets worth orders
4,2021-08-17 03:47:09+00:00,barque nations sources says valuation process ...
...,...,...
30961,2024-11-26 05:49:18+00:00,crystal integrated services bags order bc
30962,2024-12-02 03:58:51+00:00,cochon shipyards shares gain signing contract ...
30963,2024-12-02 03:59:18+00:00,rajasthan gases cells stake gujarat natural re...
30964,2024-12-04 04:00:00+00:00,revolt motor nov sales jump revolt motor repor...
30965,2024-12-04 04:00:07+00:00,china cabin november services mi vs mon

In [12]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd

# Initialize the sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

# Extend the lexicon with stock-related terms
stock_lexicon = {
    # Positive sentiment words
    "bullish": 2.0, "rally": 2.0, "breakout": 2.0, "uptrend": 2.0, 
    "rebound": 1.5, "strong": 1.5, "surge": 2.0, "profit": 2.5, 
    "gains": 2.0, "green": 1.5, "all-time high": 2.5, "above target": 2.0, 
    "outperform": 2.0, "momentum": 1.5, "buy": 1.5, "hold": 1.0, 
    "invest": 1.5, "accumulate": 1.5, "dip buying": 1.5, "earnings beat": 2.0, 
    "upside": 1.5, "break resistance": 2.0, "record highs": 2.5,

    # Negative sentiment words
    "bearish": -2.0, "crash": -3.0, "sell-off": -2.5, "downtrend": -2.0,
    "red": -1.5, "loss": -2.5, "dip": -1.5, "downside": -2.0, 
    "volatile": -1.0, "pullback": -1.5, "sell": -2.0, "downgrade": -1.5, 
    "missed expectations": -2.0, "underperform": -2.0, "correction": -2.0, 
    "drop": -2.0, "panic selling": -2.5, "bear market": -2.5, 
    "fear": -2.0, "profit warning": -2.5, "break support": -2.5,

    # Context-dependent/Neutral terms
    "dividend": 0.5, "valuation": 0.0, "consolidation": 0.0, 
    "resistance": 0.0, "support": 0.0, "price target": 0.0, 
    "overbought": -1.0, "oversold": 1.0, "neutral": 0.0, 
    "risk-on": 1.0, "risk-off": -1.0, "sideways": 0.0, "flat": 0.0
}

# Update the analyzer lexicon with stock-related terms
analyzer.lexicon.update(stock_lexicon)

# Function to determine sentiment directly from already preprocessed messages
def get_stock_sentiment_label(text):
    if not isinstance(text, str):  # Check if text is a string
        text = str(text)  # Convert to string if it's not
    scores = analyzer.polarity_scores(text)
    compound = scores['compound']
    if compound > 0.05:
        return "Positive"
    elif compound < -0.05:
        return "Negative"
    else:
        return "Neutral"

# Assuming `merged_df` is your merged dataframe and it has a 'message' column
# Apply sentiment analysis to the 'message' column
merged_df["Sentiment"] = merged_df["message"].apply(get_stock_sentiment_label)

# Save the results to a CSV file
merged_df.to_csv("Downloads\\stock_data6.csv", index=False)

# Optionally, print the first few rows of the dataframe to check the result
print(merged_df.head())

                       date  \
0 2021-08-17 03:39:23+00:00
1 2021-08-17 03:47:09+00:00
2 2021-08-17 03:47:09+00:00
3 2021-08-17 03:47:09+00:00
4 2021-08-17 03:47:09+00:00

                                             message Sentiment
0  pledge share details aurobindo parma promoter ...  Positive
1  meghmani organic meghmani organic limited megh...  Negative
2  sporting annual report china yarn ban lower in...  Negative
3                           railed gets worth orders  Positive
4  barque nations sources says valuation process ...  Positive

In [13]:
merged_df

,date,message,Sentiment
0,2021-08-17 03:39:23+00:00,pledge share details aurobindo parma promoter ...,Positive
1,2021-08-17 03:47:09+00:00,meghmani organic meghmani organic limited megh...,Negative
2,2021-08-17 03:47:09+00:00,sporting annual report china yarn ban lower in...,Negative
3,2021-08-17 03:47:09+00:00,railed gets worth orders,Positive
4,2021-08-17 03:47:09+00:00,barque nations sources says valuation process ...,Positive
...,...,...,...
30961,2024-11-26 05:49:18+00:00,crystal integrated services bags order bc,Neutral
30962,2024-12-02 03:58:51+00:00,cochon shipyards shares gain signing contract ...,Positive
30963,2024-12-02 03:59:18+00:00,rajasthan gases cells stake gujarat natural re...,Positive
30964,2024-12-04 04:00:00+00:00,revolt motor nov sales jump revolt motor repor...,Positive
30965,2024-12-04 04:00:07+00:00,china cabin november services mi vs mon,Neutral